spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-41tfcxyn.us.auth0.com/
auth0:
  audience: &audience https://api.psychology.ml/
springdoc:
  swagger-ui:
    oauth:
      clientId: CsKG8IB5gjo4XJLU0nqeaNnWvu0CDiKT
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        audience: *audience
  oAuthFlow:
    authorizationUrl: https://dev-41tfcxyn.us.auth0.com/authorize
    tokenUrl: https://dev-41tfcxyn.us.auth0.com/oauth/token
  show-actuator: true
