spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:psychology
    username: sa
    password:
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
