spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-41tfcxyn.us.auth0.com/
auth0:
  audience: &audience https://api.psychology.ml/
springdoc:
  swagger-ui:
    oauth:
      clientId: CsKG8IB5gjo4XJLU0nqeaNnWvu0CDiKT
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        audience: *audience
  oAuthFlow:
    authorizationUrl: https://dev-41tfcxyn.us.auth0.com/authorize
    tokenUrl: https://dev-41tfcxyn.us.auth0.com/oauth/token
  show-actuator: true

---
api:

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information
    unauthorized.description: The request has not been applied because it lacks valid authentication credentials for the target resource
    forbidden.description: Access is permanently forbidden

  waisIvAssessment:
    createWaisIvAssessment:
      description: Create a new WAIS-IV assessment for the current user
      notes: |
        # Normal response
        A new WAIS-IV assessment will be create with ID of the user

        # Expected error responses
        If the user isn't logged in, an **401 - Unauthorized** error message will be returned

    getWaisIvAssessment:
      description: Returns the specified WAIS-IV
      notes: |
        # Normal response
        The specified WAIS-IV assessment will be returned
        
        # Expected error responses
        If the user isn't logged in, an **401 - Unauthorized** error message will be returned

        If the user isn't the owner of the assessment, an **403 - Forbidden** error message will be returned
        
        If the specified WAIS-IV assessment isn't exist, an **404 - Not Found** error message will be returned

    getAllWaisIvAssessment:
      description: Returns an array of WAIS-IV assessments of the current user
      notes: |
        # Normal response
        If the user is logged in, server returns an array of WAIS-IV assessments of the current user
        
        # Expected error responses
        If the user isn't logged in, an **401 - Unauthorized** error message will be returned

    updateWaisIvAssessment:
      description: Update and returns the specified WAIS-IV
      notes: |
        # Normal response
        The specified WAIS-IV assessment that is updated will be returned
        
        # Expected error responses
        If the user isn't logged in, an **401 - Unauthorized** error message will be returned

        If the user isn't the owner of the assessment, an **403 - Forbidden** error message will be returned
        
        If the specified WAIS-IV assessment isn't exist, an **404 - Not Found** error message will be returned

    deleteWaisIvAssessment:
      description: Delete the specified WAIS-IV assessment
      notes: |
        # Normal response
        The specified WAIS-IV assessment will be deleted.

        # Expected error responses
        If the format of the request isn't invalid, an **400 - Bad Request** error message will be returned
        
        If the user isn't logged in, an **401 - Unauthorized** error message will be returned
        
        If the user isn't the owner of the assessment, an **403 - Forbidden** error message will be returned
        
        If the specified WAIS-IV assessment isn't exist, an **404 - Not Found** error message will be returned