apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api-route
spec:
  host: api.psychology.ml
  tls:
    termination: edge
  to:
    kind: Service
    name: agento
  port:
    targetPort: web