name: Main
on: push

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gradle jib \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} \
          --image=ghcr.io/${{ github.repository }}
