name: Main
on: push

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and package
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          gradle jib \
          -Djib.to.auth.username=$GITHUB_ACTOR \
          -Djib.to.auth.password=$GITHUB_TOKEN \
          --image=ghcr.io/$GITHUB_REPOSITORY

  arvan-pass-deploy:
    runs-on: ubuntu-latest
    needs: [build-and-package]
    container:
      image: alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare the Arvan CLI
        timeout-minutes: 2
        env:
          ARVAN_PAAS_TOKEN: Apikey f38d1a24-f27d-564e-aecc-f89aa0588f58
        run: |
          wget https://github.com/arvancloud/cli/releases/download/v1.1.3-alpha/arvan_1.1.3-alpha_linux_amd64.tar.gz
          tar -xf arvan_1.1.3-alpha_linux_amd64.tar.gz
          chmod +x ./arvan
          ./arvan update
          echo $ARVAN_PAAS_TOKEN | ./arvan login
      - name: Deploy On Arvan PaaS
        run: ./arvan paas apply -k kubernetes/overlays/arvan-paas